import { useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";

function AuthCard({ children, title, text }) { return <section className="auth-page"><div className="auth-card"><p className="eyebrow">KIRUTHIS PARLOUR</p><h1>{title}</h1><p>{text}</p>{children}</div></section>; }

export function Login() { const { login } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [form, setForm] = useState({ email: "", password: "" }); const [error, setError] = useState(""); const submit = async event => { event.preventDefault(); try { const result = await login(form.email, form.password); navigate(result.profile?.role === "admin" ? "/admin" : location.state?.from || "/my-bookings"); } catch { setError("Email or password is incorrect."); } }; return <AuthCard title="Welcome back" text="Sign in to manage your appointments."><form onSubmit={submit} className="form-stack"><label>Email<input type="email" required value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} /></label><label>Password<input type="password" required value={form.password} onChange={event => setForm({ ...form, password: event.target.value })} /></label>{error && <p className="error">{error}</p>}<button className="button">Sign in</button><p>New here? <Link to="/register">Create an account</Link></p></form></AuthCard>; }

export function Register() { const { register } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ name: "", email: "", phone: "", password: "", confirm: "" }); const [error, setError] = useState(""); const submit = async event => { event.preventDefault(); if (form.password !== form.confirm) return setError("Passwords do not match."); try { await register(form); navigate("/my-bookings"); } catch { setError("We could not create your account. Check your details and try again."); } }; return <AuthCard title="Make time for yourself" text="Create an account to book and manage appointments."><form onSubmit={submit} className="form-stack"><label>Full name<input required value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} /></label><label>Email<input type="email" required value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} /></label><label>Phone<input required value={form.phone} onChange={event => setForm({ ...form, phone: event.target.value })} /></label><label>Password<input type="password" minLength="6" required value={form.password} onChange={event => setForm({ ...form, password: event.target.value })} /></label><label>Confirm password<input type="password" required value={form.confirm} onChange={event => setForm({ ...form, confirm: event.target.value })} /></label>{error && <p className="error">{error}</p>}<button className="button">Create account</button><p>Already registered? <Link to="/login">Sign in</Link></p></form></AuthCard>; }
